"""Feature engineering for MIAX14 Hackathon - Index prediction."""

import os
import numpy as np
import pandas as pd

from sentiment import build_news_features

INDICES = ["Index_A", "Index_B", "Index_C", "Index_D", "Index_E", "Index_F"]
# Index_D ≈ 1.0001815 * Index_A(t-1) + 3.116  (R²=0.999995)
INDEX_D_COEF = 1.0001815263
INDEX_D_INTERCEPT = 3.11605738

LAG_DAYS = [1, 2, 3, 5, 10, 21, 63]
ROLL_WINDOWS = [5, 10, 21, 63]
MACRO_COLS = ["Crude_Vitality", "Lumina_Reserve", "Capital_Cost_Index"]
NET_COLS = ["Network_Activity_Score", "Active_Digital_Nodes"]
NEWS_COLS = ["news_count", "news_sentiment", "news_sentiment_std"]


def load_data(data_dir: str = "data") -> dict:
    train_idx = pd.read_csv(f"{data_dir}/train_indices.csv", parse_dates=["Date"], index_col="Date")
    train_macro = pd.read_csv(f"{data_dir}/train_macro_factors.csv", parse_dates=["Date"], index_col="Date")
    train_net = pd.read_csv(f"{data_dir}/train_network_metrics.csv", parse_dates=["Date"], index_col="Date")
    test_macro = pd.read_csv(f"{data_dir}/test_macro_factors.csv", parse_dates=["Date"], index_col="Date")
    test_net = pd.read_csv(f"{data_dir}/test_network_metrics.csv", parse_dates=["Date"], index_col="Date")
    train_news = pd.read_csv(f"{data_dir}/train_news.csv", parse_dates=["Date"])
    test_news = pd.read_csv(f"{data_dir}/test_news.csv", parse_dates=["Date"])

    # Strip whitespace from test index dates
    if test_macro.index.dtype == object:
        test_macro.index = pd.to_datetime(test_macro.index.str.strip())

    return {
        "train_idx": train_idx,
        "train_macro": train_macro,
        "train_net": train_net,
        "test_macro": test_macro,
        "test_net": test_net,
        "train_news": train_news,
        "test_news": test_news,
    }


def _lag_cols(df: pd.DataFrame, cols: list, lags: list) -> pd.DataFrame:
    new = {f"{c}_lag{l}": df[c].shift(l) for c in cols for l in lags}
    return pd.concat([df, pd.DataFrame(new, index=df.index)], axis=1)


def _roll_cols(df: pd.DataFrame, cols: list, windows: list) -> pd.DataFrame:
    new = {}
    for c in cols:
        for w in windows:
            new[f"{c}_roll_mean{w}"] = df[c].shift(1).rolling(w).mean()
            new[f"{c}_roll_std{w}"] = df[c].shift(1).rolling(w).std()
    return pd.concat([df, pd.DataFrame(new, index=df.index)], axis=1)


def _return_cols(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    # shift(1) so ret1 at time t = return from t-2 to t-1 (no leakage of current price)
    new = {}
    for c in cols:
        new[f"{c}_ret1"] = df[c].pct_change(1).shift(1)
        new[f"{c}_ret5"] = df[c].pct_change(5).shift(1)
        new[f"{c}_ret21"] = df[c].pct_change(21).shift(1)
    return pd.concat([df, pd.DataFrame(new, index=df.index)], axis=1)


def _add_index_d_ghost(df: pd.DataFrame) -> pd.DataFrame:
    """Explicit formula: Index_D(t) ≈ coef * Index_A(t-1) + intercept."""
    df = df.copy()
    df["Index_D_ghost"] = INDEX_D_COEF * df["Index_A"].shift(1) + INDEX_D_INTERCEPT
    return df


def _add_calendar(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["day_of_week"] = df.index.dayofweek
    df["month"] = df.index.month
    df["quarter"] = df.index.quarter
    return df


def _load_finbert(data_dir: str, split: str) -> pd.DataFrame | None:
    """Load pre-computed FinBERT features if available (generated by notebook 04)."""
    path = os.path.join(data_dir, f"finbert_sentiment_{split}.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path, parse_dates=["Date"], index_col="Date")
    return df


def build_feature_matrix(data: dict, data_dir: str = "data") -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build full feature matrix for training and (exogenous) test features."""
    train_idx = data["train_idx"].copy()
    train_macro = data["train_macro"].copy()
    train_net = data["train_net"].copy()
    test_macro = data["test_macro"].copy()
    test_net = data["test_net"].copy()

    # Keyword sentiment (always available)
    news_train = build_news_features(data["train_news"])
    news_test = build_news_features(data["test_news"])

    # FinBERT sentiment (optional — generated by notebook 04)
    finbert_train = _load_finbert(data_dir, "train")
    finbert_test = _load_finbert(data_dir, "test")
    if finbert_train is not None:
        print("  FinBERT features: loaded ✓")
    else:
        print("  FinBERT features: not found (run notebook 04 to generate)")

    # ── TRAINING FEATURES ────────────────────────────────────────────────
    feat = train_idx.join(train_macro, how="left")
    # Forward-fill macro gaps (1054 trading days missing from source CSV)
    feat[MACRO_COLS] = feat[MACRO_COLS].ffill()
    feat = feat.join(train_net, how="left")
    feat = feat.join(news_train, how="left")
    for c in NEWS_COLS:
        if c not in feat.columns:
            feat[c] = 0
        else:
            feat[c] = feat[c].fillna(0)

    if finbert_train is not None:
        finbert_cols = list(finbert_train.columns)
        feat = feat.join(finbert_train, how="left")
        feat[finbert_cols] = feat[finbert_cols].fillna(0)
    else:
        finbert_cols = []

    feat = _add_calendar(feat)
    feat = _add_index_d_ghost(feat)
    feat = _lag_cols(feat, INDICES, LAG_DAYS)
    feat = _roll_cols(feat, INDICES, ROLL_WINDOWS)
    feat = _return_cols(feat, INDICES)
    feat = _lag_cols(feat, MACRO_COLS, [1, 5, 21])
    feat = _roll_cols(feat, MACRO_COLS, [5, 21])
    feat = _lag_cols(feat, NET_COLS, [1, 5, 21])
    feat = _roll_cols(feat, NET_COLS, [5, 21])
    feat = _lag_cols(feat, NEWS_COLS, [1, 5])
    if finbert_cols:
        feat = _lag_cols(feat, finbert_cols, [1, 5])
    feat.dropna(inplace=True)

    # ── TEST EXOGENOUS FEATURES (no index values yet) ────────────────────
    # Base date index = ALL test dates. test_macro only has 173 of the 252
    # trading dates, while test_net has all 252; use their union so the
    # submission covers every required date.
    all_test_dates = test_net.index.union(test_macro.index).sort_values()
    test_feat = pd.DataFrame(index=all_test_dates)
    test_feat = test_feat.join(test_macro, how="left")
    # Forward-fill macro on the 79 dates missing from test_macro
    test_feat[MACRO_COLS] = test_feat[MACRO_COLS].ffill().bfill()
    test_feat = test_feat.join(test_net, how="left")
    test_feat = test_feat.join(news_test, how="left")
    for c in NEWS_COLS:
        if c not in test_feat.columns:
            test_feat[c] = 0
        else:
            test_feat[c] = test_feat[c].fillna(0)

    if finbert_test is not None:
        test_feat = test_feat.join(finbert_test, how="left")
        test_feat[finbert_cols] = test_feat[finbert_cols].fillna(0)
    elif finbert_cols:
        for c in finbert_cols:
            test_feat[c] = 0

    test_feat = _add_calendar(test_feat)

    return feat, test_feat
